# Gree Climate Integration - Manual Configuration Example
# 
# This file contains all possible configuration options for the Gree Climate integration
# when using YAML configuration instead of the UI config flow.
#
# Copy the sections you need to your configuration.yaml file.
#
# If an option is not provided the default values will be used.
# For option lists, pass empty list ([]) to disable the option.
#
# MAC address Format can be XX:XX:XX:XX:XX:XX, XX-XX-XX-XX-XX-XX, xxxxxxxxxxxx 
#
# For VRF units the MAC is usually xxxxxxxxxxxx@yyyyyyyyyyyy where 
# the first part (x) is the sub device MAC and the second (y) the main device MAC
# In this case it is preferred to place the main device MAC on the top config and 
# the sub device MAC on the device list config


gree_custom:
  - host: "192.168.1.100" # IP Address of AC | required | str
    mac: "20-FA-BB-12-34-56" # MAC Address of Main AC Unit | required | str
    advanced:
      port: 7000 # Port number to connect to the device | int | default = 7000
      encryption_version: 2 # The encryption version to use with the device | options = "Auto-Detect", 1, 2 | default = "Auto-Detect"
      encryption_key: "my_device_key" # Custom encryption key | str | default = <fetched from device>
      uid: 0 # Device identifier which is not needed for all devices, can be sniffed if required | positive int | default = 0
      disable_available_check: false # boolean | default = false
      max_online_attempts: 3 # Number connection attempts made with device before it is marked as unavailable | positive int | default = 5
      timeout: 10 # Seconds before a connection attempt times out |  positive int (seconds) | default = 10
    devices: # List of the devices that will be created (optional if only one device and no configuration required)
      - device_name: "Gree AC" # Name for the AC unit | str | default = "Gree AC <MAC>]"
        mac: "20-FA-BB-12-34-56" # MAC Address of the sub AC unit (same as Main device if not VRF) | required | str
        hvac_modes: # Standard Home Assistant HVAC Modes to enable | list | options = ["auto", "cool", "dry", "fan_only", "heat", "off"] | default = all options
          - "auto"
          - "cool"
          - "dry"
          - "fan_only"
          - "heat"
          - "off"
        fan_modes: # Supported fan modes | list | options = ["Auto", "Low", "MediumLow", "Medium", "MediumHigh", "High", "turbo", "quiet"] | default = all options
          - "Auto"
          - "Low"
          - "MediumLow"
          - "Medium"
          - "MediumHigh"
          - "High"
          - "turbo"
          - "quiet"
        swing_modes: # Supported vertical swing modes | list | options = ["Default", "FullSwing", "FixedUpper", "FixedUpperMiddle", "FixedMiddle", "FixedLowerMiddle", "FixedLower", "SwingLower", "SwingLowerMiddle", "SwingMiddle", "SwingUpperMiddle", "SwingUpper"] | default = all options
          - "Default"
          - "FullSwing"
          - "FixedUpper"
          - "FixedUpperMiddle"
          - "FixedMiddle"
          - "FixedLowerMiddle"
          - "FixedLower"
          - "SwingLower"
          - "SwingLowerMiddle"
          - "SwingMiddle"
          - "SwingUpperMiddle"
          - "SwingUpper"
        swing_horizontal_modes: # Supported horizontal swing modes | list | options = ["Default", "FullSwing", "Left", "LeftCenter", "Center", "RightCenter", "Right"] | default = all options
          - "Default"
          - "FullSwing"
          - "Left"
          - "LeftCenter"
          - "Center"
          - "RightCenter"
          - "Right"
        features: # Supported device features | list | options = ["beeper", "air", "xfan", "sleep", "eightdegheat", "lights", "health", "anti_direct_blow", "powersave", "light_sensor"] | default = all options
          - "beeper"
          - "air"
          - "xfan"
          - "sleep"
          - "eightdegheat"
          - "lights"
          - "health"
          - "anti_direct_blow"
          - "powersave"
          - "light_sensor"
        target_temp_step: 1 # Number of degrees increase or decrease when changing the temperature | 0.5 < int < 5, 0.5 increments | default = 1
        external_temperature_sensor: "None" # Sets a given temperature sensor as the sensor for the AC | str (Entity ID) | default = "None"
        external_humidity_sensor: "None" # Sets a given humidity sensor as the sensor for the AC | str (Entity ID) | default = "None"
        restore_states: true # Wether to restore the last HA state to device when HA starts | bool | default = true


# Example for multiple AC units:
# gree_custom:
#   - host: "192.168.1.101"
#     mac: "20-FA-BB-12-34-56"
#     advanced:
#       encryption_version: 2
  
#   - host: "192.168.1.102"
#     mac: "20-FA-BB-12-34-57"
#     devices:
#       - name: "Gree AC"
#         mac: "20-FA-BB-12-34-57"
